[game]
screen_width = 900
screen_height = 600
fps = 60
background_color = [34, 139, 34]

[game.grid]
rows = 5
cols = 9
cell_width = 80
cell_height = 100
start_x = 80
start_y = 80

[plants.sunflower]
name = "向日葵"
cost = 50
health = 100
width = 60
height = 80
color = [255, 255, 0]
sun_production_interval = 24.0
sun_amount = 25

[plants.peashooter]
name = "豌豆射手"
cost = 100
health = 100
width = 60
height = 80
color = [0, 200, 0]
fire_rate = 1.5
projectile_damage = 20
projectile_speed = 400

[plants.wallnut]
name = "坚果墙"
cost = 50
health = 400
width = 60
height = 80
color = [139, 69, 19]

[plants.snow_pea]
name = "寒冰射手"
cost = 175
health = 100
width = 60
height = 80
color = [135, 206, 250]
fire_rate = 1.5
projectile_damage = 20
projectile_speed = 400
slow_effect = 0.5
slow_duration = 5.0

[plants.cherry_bomb]
name = "樱桃炸弹"
cost = 150
health = 100
width = 60
height = 80
color = [220, 20, 60]
explosion_radius = 100
explosion_damage = 1800

[plants.potato_mine]
name = "土豆雷"
cost = 25
health = 100
width = 60
height = 40
color = [160, 82, 45]
arm_time = 14.0
explosion_damage = 1800

[plants.repeater]
name = "双发射手"
cost = 200
health = 100
width = 60
height = 80
color = [0, 150, 0]
fire_rate = 1.5
projectile_damage = 20
projectile_speed = 400
shots_per_fire = 2

[plants.chomper]
name = "大嘴花"
cost = 150
health = 100
width = 80
height = 80
color = [128, 0, 128]
chomp_cooldown = 42.0
instant_kill = true

[plants.threepeater]
name = "三线射手"
cost = 325
health = 100
width = 60
height = 80
color = [0, 180, 0]
fire_rate = 1.5
projectile_damage = 20
projectile_speed = 400
rows = 3

[plants.melon_pult]
name = "西瓜投手"
cost = 300
health = 100
width = 70
height = 80
color = [0, 150, 0]
fire_rate = 2.5
projectile_damage = 80
projectile_speed = 300
splash_radius = 50
splash_damage = 40

[plants.winter_melon]
name = "冰西瓜"
cost = 500
health = 100
width = 70
height = 80
color = [100, 150, 200]
fire_rate = 2.5
projectile_damage = 80
projectile_speed = 300
splash_radius = 50
splash_damage = 40
slow_effect = 0.5
slow_duration = 5.0

[plants.tall_nut]
name = "高坚果"
cost = 125
health = 800
width = 60
height = 100
color = [160, 120, 80]

[plants.spikeweed]
name = "地刺"
cost = 100
health = 100
width = 60
height = 40
color = [100, 100, 100]
damage_per_second = 20

[plants.magnet_shroom]
name = "磁力菇"
cost = 100
health = 100
width = 60
height = 70
color = [128, 0, 128]
magnet_range = 100
magnet_cooldown = 10.0

[plants.pumpkin]
name = "南瓜头"
cost = 125
health = 400
width = 70
height = 70
color = [255, 140, 0]
